spring.application.name=minimarket
# Configuracion de H2 en memoria
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# Configuracion de JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Jwt
minimarket.app.jwtSecret=dGVzdFNlY3JldEtleVBhcmFNaW5pbWFya2V0UGx1czIwMjU=
minimarket.app.jwtExpirationMs=86400000
